server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: backend_product
          uri: http://localhost:8060
          predicates:
            - Path=/api/product/**,
        - id: backend-user
          uri: http://localhost:8070
          predicates:
            - Path=/api/user/**,

        - id: frontend
          uri: http://localhost:8081
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/** /productSearches/**
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/shippings/** 
        - id: inventory
          uri: http://inventory:8080
          predicates:
            - Path=/inventories/** 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=/customers/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080